apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-container
  template:
    metadata:
      labels:
        app: order-container
    spec:
      containers:
      - name: order-container
        image: us-central1-docker.pkg.dev/gothic-avenue-470908-m7/onlinestore/maalami/springbootorder
        ports:
        - containerPort: 8445
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-container
  ports:
    - port: 8445
      targetPort: 8445
  type: ClusterIP