name: kubernetes-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          install_components: 'gke-gcloud-auth-plugin'

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and push Docker images
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          TAG: ${{ github.sha }}
        run: |
          # Store
          docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/onlinestore/maalami/springbootstore:$TAG -f k8s/Dockerfile .
          docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/onlinestore/maalami/springbootstore:$TAG

      - name: Deploy to GKE
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          TAG: ${{ github.sha }}
        run: |
          gcloud container clusters get-credentials onlinestore-cluster --region us-central1 --project $GOOGLE_PROJECT

          # Actualizar los Deployment.yaml con el nuevo TAG
          for file in k8s/store-deployment.yaml; do
            sed -i "s|GOOGLE_PROJECT|$GOOGLE_PROJECT|g" $file
            # Solo cambiar el tag si es un microservicio tuyo
            if grep -q "springboot" $file || grep -q "mysql" $file || grep -q "nginx" $file; then
              sed -i "s|:latest|:$TAG|g" $file
            fi
            kubectl apply -f $file
          done
