name: kubernetes-deploy
#update
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login a DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir y publicar imagen
        run: |
          IMAGE=maalami/springbootstore:latest
          docker build -t $IMAGE -f k8s/Dockerfile .
          docker push $IMAGE

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Update deployment image
        run: |
          IMAGE_NAME=maalami/springbootstore:latest
          kubectl apply -f k8s/store-deployment.yaml
          kubectl set image deployment/store-container store-container=$IMAGE_NAME


      - name: Verify rollout
        run: kubectl rollout restart deployment/store-container


    



