name: kubernetes-deploy
#update
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # 2. Login en Docker Hub
      - name: Log in to OCIR
        uses: docker/login-action@v2
        with: 
          registry: us-chicago-1.ocir.io
          username: ${{ secrets.OCIR_USERNAME }} 
          password: ${{ secrets.OCIR_PASSWORD }}

      - name: Build and push Docker images
        env:
          NAMESPACE: ${{ secrets.OCIR_NAMESPACE }}
          TAG: ${{ github.sha }}
        run: |
          IMAGE=us-chicago-1.ocir.io/$NAMESPACE/springbootstore/store:$TAG
          docker build -t $IMAGE -f k8s/Dockerfile .
          docker push $IMAGE
