name: kubernetes-deploy
#update
on:
  push:
    branches:
      - main

env:
  TAG: ${{ github.sha }}
  NAMESPACE: ${{ secrets.OCIR_NAMESPACE }}
  IMAGE: us-chicago-1.ocir.io/$NAMESPACE/springbootstore/store:$TAG

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # 2. Login en Docker Hub
      - name: Log in to OCIR
        uses: docker/login-action@v2
        with: 
          registry: us-chicago-1.ocir.io
          username: ${{ secrets.OCIR_USERNAME }} 
          password: ${{ secrets.OCIR_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker build -t $IMAGE -f k8s/Dockerfile .
          docker push $IMAGE

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Update deployment image
        run: |
          kubectl set image deployment/store-container store-container=$IMAGE:$TAG --record || true
          kubectl apply -f k8s/store-deployment.yaml

      - name: Verify rollout
        run: kubectl rollout status deployment/store-container