name: kubernetes-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          install_components: 'gke-gcloud-auth-plugin'

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and push Docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/onlinestore/nginx:latest .
          docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/onlinestore/nginx:latest

      - name: Deploy to GKE
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud container clusters get-credentials onlinestore-cluster --region us-central1 --project $GOOGLE_PROJECT
          for file in k8s/*-deployment.yaml; do
            sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" $file
            kubectl apply -f $file
          done

#        ### GATEWAY
#        - name: Deploy Gateway App (Deployment)
#          uses: actions-hub/kubectl@master
#          with:
#            args: apply -f k8s/gateway-deployment.yaml
#        ### STORE
#        - name: Deploy Store App (Deployment)
#          uses: actions-hub/kubectl@master
#          with:
#            args: apply -f k8s/store-deployment.yaml
#        ### INVENTORY
#        - name: Deploy Inventory App (Deployment)
#          uses: actions-hub/kubectl@master
#          with:
#            args: apply -f k8s/inventory-deployment.yaml
#        ### ORDER
#        - name: Deploy Order App (Deployment)
#          uses: actions-hub/kubectl@master
#          with:
#            args: apply -f k8s/order-deployment.yaml
#        ### REDIS
#        - name: Deploy Redis App (Deployment)
#          uses: actions-hub/kubectl@master
#          with:
#            args: apply -f k8s/redis-deployment.yaml
#        ### MYSQL
#        - name: Deploy Mysql App (Deployment)
#          uses: actions-hub/kubectl@master
#          with:
#            args: apply -f k8s/mysql-deployment.yaml